other
style
 ^ '
#sidebar {
	border-radius: 25px;
	height: 400px;
	width: 180px;
	position: absolute;
	text-align: center;
	background-color: gray;
	background-repeat: repeat-x;
	border-style: ridge;
	margin-left: -4px;
	}
#info-area {
	margin-left: 200px;
}
#field-names {
	float: left;
	margin-right: 30px;
}
#search-types {
	float: left;
	margin-right: 30px;
}
#summary {
	float: left;
	margin-right: 30px;
}
#close-button form fieldset{
	border: none;
}
#close-button input.submit {
	width: 150px;
	height: 35px;
	font-size: medium;
	background-color: lavender;
	border-radius: 12px;
	margin-right: 550px;
	float: right;
}
.reportColumn 
{
	font-family:"Times New Roman", Times, serif;
	font-size: 20px;
	/*border-radius: 6px; */
	}
 body{
     background-color: silver;
 }
table {
	display: table;
	border-collapse: separate;
	border-spacing: 2px;
	border-color: red;
}
th, td {
	display: table-cell;
	vertical-align: inherit;
	border-bottom: white;
	border-width: 1px;
	border-style: inset;
	width: 1px;
	white-space: nowrap;
}

#banner {
	margin-top: -8px;
}
#tabs-section {
	margin-top: 70px; 
	margin-left: 180px;
	 padding-left: 5px;
} 
#header{
     width: 100%;
     height: 40px;
     padding-left: 5px;
     background-color: #d7eeee;
 }

#content{
     font-family: arial;
     text-align: justify;
     margin-left: 180px;
     margin-right: 5px;
     padding-left: 5px;
     padding-right: 5px;
     padding-top: 5px;
     padding-bottom: 5px;
     background-color: silver;
 }

 #tabs{
    list-style-type: none;
	margin-left: -40px;
 }

#tabs li{
     display: inline;
 }

#tabs li a{
     text-align: center;
	 border-radius: 20px;
     width: 80px;
     height: 25px;
     color: #000;
     background-color: #EEEEEE;
     margin: 1px;
     padding: 0.5em;
     font-size: 30px;
     text-decoration: none
; }

#tabs li a:hover{
     background-color: gray; 
 } 

a img {
	padding-left: 4px;
	padding-top: 4px;
}
.batch {
	text-align: center;}
 .hidden {
	position: absolute;
	left: -10000px;
	top: auto;
	width: 1px;
	height: 1px;
	overflow: hidden;}'