other
getXMLFormInstance

	^'<?xml version="1.0" encoding="UTF-8"?>
<form>
    <section-1>
        <section-1-iteration>
            <name>bruno</name>
            <surname>buzzo</surname>
            <phone>4444444445</phone>
            <mail>b@e.tv</mail>
            <boolean>true</boolean>
            <section-7>
                <control-8/>
                <mobile>09998</mobile>
                <grid-10>
                    <moneySubject>3</moneySubject>
                    <quantity>5005</quantity>
                    <currency>122.5</currency>
                </grid-10>
                <grid-10>
                    <quantity/>
                    <currency/>
                    <moneySubject/>
                </grid-10>
                <grid-10>
                    <quantity/>
                    <currency/>
                    <moneySubject/>
                </grid-10>
            </section-7>
        </section-1-iteration>
    </section-1>
    <section-14>
        <date1>2016-04-08</date1>
        <dateTime>2016-04-13T12:50:00</dateTime>
        <date2>2006-07-07</date2>
        <date3>2016-04-19</date3>
		<time>8:48:38 pm</time>
        <details>these are the details</details>
        <type>1</type>
        <grid-19>
            <options>2 1</options>
            <otherOptions>2</otherOptions>
        </grid-19>
        <section-24>
            <formatedText>&lt;ol&gt;&lt;li&gt;this is a &lt;strong style="line-height: 1.5em;"&gt;formatted&lt;/strong&gt; &lt;em style="line-height: 1.5em;"&gt;text&lt;/em&gt;&lt;/li&gt;&lt;li&gt;&lt;em style="line-height: 1.5em;"&gt;hello&lt;/em&gt;&lt;/li&gt;&lt;/ol&gt;&lt;div&gt;
&lt;ul&gt;&lt;li&gt;&lt;strong&gt;&lt;em&gt;test&lt;/em&gt;&lt;/strong&gt;&lt;/li&gt;&lt;li&gt;&lt;strong&gt;&lt;em&gt;sadf&lt;/em&gt;&lt;/strong&gt;&lt;/li&gt;&lt;/ul&gt;
&lt;strong&gt;&lt;em&gt;&lt;br&gt;&lt;/em&gt;&lt;/strong&gt;&lt;/div&gt;</formatedText>
            <fileAttachment filename="" mediatype="" size=""/>
            <imageAttachment filename="" mediatype="" size=""/>
            <imageAnnotation>
                <image filename="" mediatype="" size=""/>
                <annotation>data:image/png;base64,</annotation>
            </imageAnnotation>
            <autocomplete label=""/>
        </section-24>
    </section-14>
</form>'