other
style
 ^ '
a img {
	padding-left: 4px;
	padding-top: 4px;
}
#banner {
	margin-top: -8px;
}
.batch {
	text-align: center;}
body{
     background-color: silver;
 }
#content{
    font-family: arial;
    text-align: justify;
  /*   margin-left: 180px;*/
    margin-right: 5px;
    padding-left: 5px;
    padding-right: 5px;
    padding-bottom: 5px;
    background-color: silver;
}
#export-component { 
	/*display: flex;*/
	margin-top: 10px;
	margin-bottom: 10px;
    width: 45%;
    margin-right: auto;
	margin-left: auto;
	float: inherit;
}
#export-component form { 
    width: 60%;
}
#export-component fieldset {
	margin-top: 10px;
	border-radius: 15px;
	background-color: beige;
	margin-left: -30px;
}
#export-component fieldset label {
	display: block; 
	margin-top: 8px;
}
#export-component fieldset legend {
	background-color: beige; 
	border-radius: 5px;
}
#export-component input.submit {
	float: right;
	width: 140px;
	height: 30px;
	font-size: medium;
	background-color: lavender;
	border-radius: 12px;
	margin-right: 5px;
}
#formularios-def-report {
    height: 360px;
	overflow: auto;
}
#formularios-def-report table {
    margin: auto;
}
#formularios-def-report table fieldset {
    margin: auto;
}
#formularios-def-report tbody a {
	text-decoration: none;
	color: black;
}
#formularios-inst-report {
    height: auto;
	overflow: auto;
}
#formularios-inst-report form{
	height: auto;
	overflow: auto;
	margin-left: auto;
	margin-right: auto;
	width: 90%;
}
#formularios-inst-report table {
    margin: auto;
}
#formularios-inst-report tbody a {
	text-decoration: none;
	color: black;
}
 #formularios-publicados {
	height: 45px;
	width: 100%;
	background-color: honeydew;
	border-radius: 10px;
	font-family: "Trebuchet MS";
	font-size: xx-large;
	text-align: center;
}
#header{
     width: 100%;
     height: 40px;
     padding-left: 5px;
     background-color: #d7eeee;
 }
.hidden {
	position: absolute;
	left: -10000px;
	top: auto;
	width: 1px;
	height: 1px;
	overflow: hidden;
}
#imported-data {
	margin-left: 200px;
	width: 950px;
	margin-top: 40px;
}
#imported-data table {
	text-align: center;
}
#orbeon-applications { 
	/*display: flex;*/
	margin-top: 10px;
	margin-bottom: 10px;
    width: 45%;
    margin-right: auto;
	margin-left: auto;
	float: inherit;
}
#orbeon-applications fieldset {
	margin-top: 10px;
	border-radius: 15px;
	background-color: beige;
	margin-left: -30px;
}
#orbeon-applications fieldset legend {
	background-color: beige; 
	border-radius: 5px;
}
#orbeon-applications form select {
	height: 30px;
	width: 250px;
	background-color: lavender;
	font-size: larger;
	border-radius: 8px;
	margin-right: 5px;
}
#orbeon-applications input.submit {
	width: 180px;
	height: 35px;
	font-size: medium;
	background-color: lavender;
	border-radius: 12px;
	margin-right: 5px;
}
#operations-buttons fieldset {
	margin-left: auto;
	margin-top: 10px;
	margin-right: auto;
	/*width: 470px;*/
	width: 52%;
	padding-left: 100px;
}
#operations-buttons input.submit {
	width: 150px;
	height: 35px;
	font-size: medium;
	background-color: lavender;
	border-radius: 12px;
	margin-right: 5px;
}
#operations-buttons-inst fieldset {
	margin-left: auto;
	margin-top: 10px;
	margin-right: auto;
	/*width: 470px;*/
	width: 40%;
	padding-left: 100px;
}
#orbeon-definitions {
	/*margin-left: 195px;
	margin-top: -335px;*/
	margin-bottom: 10px;
	/* overflow: auto; */
/*	border-style: inset;*/
	border-width: 3px;
}
#orbeon-instances {
/*	overflow: auto;*/
 /*   height: 500px; */
/*	border-style: inset;*/
	border-width: 3px;
	margin-top: 35px;
}
#orbeon-instances form {
	border-radius: 10px;
	display: inline-block;
	margin-bottom: 10px;
}
#orbeon-instances fieldset {
	border: 0;
}
#orbeon-instances form select {
	height: 25px;
	width: 325px;
	background-color: lavender;
	font-size: medium;
	border-radius: 8px;
	margin-left: 10px;
	margin-right: 10px;
}
#orbeon-instances input.submit {
	width: 120px;
	height: 30px;
	font-size: medium;
	background-color: lavender;
	border-radius: 12px;
}
#orbeon-instances input.text {
	width: 150px;
	height: 25px;
	font-size: medium;
	background-color: lavender;
	border-radius: 10px;
	margin-left: 10px;
	margin-right: 10px;
}
#orbeon-instances-def {
/*	margin-left: 195px;*/
	margin-top: -301px;
}
#organismo-formulario {
	margin-top: 10px;
	border-radius: 15px;
	background-color: beige;
	border-style: outset;
	border-width: 2px;
	height: 30px;
	font-size: 20px;
}
.reportColumn 
{
	font-family: "Trebuchet MS";
	font-size: 18px;
	/*border-radius: 6px; */
	text-align: center;
}
#search-buttons {
	display: inline-block;
}
#search-form {
	width: 70%;
	margin: 0 auto;
}
#search-form form  {
	border-radius: 10px;
	border-style: outset;
	border-width: 2px;
	display: inline-block;
	margin-bottom: 10px;
	background-color: beige;
}
#sidebar {
	border-radius: 25px;
	height: 400px;
	width: 180px;
	position: absolute;
	text-align: center;
	background-color: gray;
	background-repeat: repeat-x;
	border-style: ridge;
	margin-left: -4px;
}
#search-version {
	width: 30%;
	margin: 0 auto;
}
#search-version form fieldset select {
	width: 80px;
}
.sort-buttons {
	float: initial;
	display: -webkit-inline-box;
}	
table {
	display: table;
	border-collapse: separate;
	border-spacing: 2px;
/*	table-layout: fixed;*/
	width: 1000px;
}
#tabs-section {
	margin-top: 70px; 
	margin-left: 180px;
	 padding-left: 5px;
} 
#tabs{
    list-style-type: none;
	margin-left: -40px;
 }
#tabs li{
     display: inline;
 }
#tabs li a{
     text-align: center;
	 border-radius: 20px;
     width: 80px;
     height: 25px;
     color: #000;
     background-color: #EEEEEE;
     margin: 1px;
     padding: 0.5em;
     font-size: 30px;
     text-decoration: none
; }
#tabs li a:hover{
     background-color: gray; 
 } 
th, td {
	display: table-cell;
	vertical-align: inherit;
	border-bottom: white;
	border-width: 1px;
	border-style: inset;
	width: 1px;
	white-space: nowrap;
}
#top-bar { 
/*	margin-left: 200px; */
	padding-right: 20px;
	border-radius: 20px;
	height: 30px;
	text-align: right;
	float: right;
	padding-left: 10px;
	background-color: beige;
}'