visa process
formInstance_ue_check_accounts_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>JKPZlrQcBM9Rlylz</s>
			<k>uTZ1BcE9CeygeV8T</k>
			<uuid>e7139b6b-a0aa-4113-9e2a-01911fd7ae50</uuid>
			<oop>7459019521</oop>
			<assignmentOop>7459021569</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>andrew po</username>
			<rol>[properties officer]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<citizenName>Bruno</citizenName>
			<citizenSurname>Buzzi Brassesco</citizenSurname>
			<originCountry>uruguay</originCountry>
			<citizenId>37673595</citizenId>
		</grid-3>
	</section-12>
	<section-16>
		<grid-4>
			<accountsDetails>&lt;div&gt;3 houses value $5.000.000&lt;/div&gt;</accountsDetails>
		</grid-4>
	</section-16>
</form>'