visa process
formInstance_ue_applicant_home_office_report_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>LvyCHXZ8NXzlaNBp</s>
			<k>7zFK6EKlVLZ5QqFk</k>
			<uuid>501950e9-1207-49d3-a5a2-4d5af58e4911</uuid>
			<oop>7428564225</oop>
			<assignmentOop>7428566529</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>andrew vc</username>
			<rol>[visa checker]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<citizenName>Bruno</citizenName>
			<citizenSurname>Buzzi Brassesco</citizenSurname>
			<originCountry>uruguay</originCountry>
			<citizenId>37673595</citizenId>
		</grid-3>
	</section-12>
	<section-16>
		<grid-17>
			<grid-17-iteration>
				<offenseDate>2016-02-24</offenseDate>
				<offenseType>public-missbehavior</offenseType>
				<offenseExpiration>2016-02-25</offenseExpiration>
			</grid-17-iteration>
		</grid-17>
	</section-16>
</form>'