library
formInstance_ue_library_composed_form

	^'<?xml version="1.0" encoding="UTF-8"?><form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
                    <internal-section><grid-1>
                            <s>s1</s>
                            <k>k1</k>
                            <uuid>u1</uuid>
                            <oop>op1</oop>
                            <assignmentOop>op2</assignmentOop>
                        </grid-1>
                    </internal-section>
                    <login-section><grid-2>
                            <username>bruno</username>
                            <rol>admin</rol>
                            <processId>12</processId>
                        </grid-2>
                    </login-section>
                    <section-name><grid-1>
                            <name>john</name>
                            <surname>conor</surname>
                        </grid-1>
                    </section-name>
                    <section-address><grid-2>
                            <street>av end</street>
                            <number>123</number>
                            <subNumber>543</subNumber>
                        </grid-2>
                    </section-address>
                </form>'