simple registratio process
formInstance_st_registration_approval

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>Z-TDf9jjx6pSXqt9</s>
			<k>LKOKSshYqrljrnOQ</k>
			<uuid>8c9d30cf-8bd2-4de2-9c33-132038911f84</uuid>
			<oop>7687898113</oop>
			<assignmentOop>7687910401</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>alberto</username>
			<rol>[Vendor][rrhh][ing civil][admin][approver]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<result>approved</result>
		</grid-3>
	</section-12>
</form>'