energy recursive
formInstance_agesic_energy_recursive

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<Datos-generales>
		<grid-1>
			<nombre>Antofagasta</nombre>
			<rut>987654</rut>
		</grid-1>
		<grid-2>
			<ciiu2>02</ciiu2>
			<control-52>2</control-52>
		</grid-2>
		<grid-3>
			<pyme>1</pyme>
			<empleados>1 3</empleados>
			<ventasAnuales>2</ventasAnuales>
			<certificado_pyme filename="license.xml" mediatype="text/xml" size="624">/fr/service/persistence/crud/agesic/energy-recursive/data/5ae7464ba7b46d72ed57a962a8b8a892782ca766/0ab0625fc62b526bcdac78eab14f2261b947b4a2.bin</certificado_pyme>
		</grid-3>
	</Datos-generales>
	<section-41>
		<grid-4>
			<nombreDirectivo>Bill Gates</nombreDirectivo>
			<cargoDirectivo>CEO</cargoDirectivo>
			<direccionDirectivo>California 45689</direccionDirectivo>
			<telefonoDirectivo>0994444</telefonoDirectivo>
			<emailDirectivo>bill@bill.com</emailDirectivo>
		</grid-4>
	</section-41>
	<section-53>
		<section-53-iteration>
			<grid-5>
				<nombreCertificador>Steve Jobs</nombreCertificador>
				<cargoCertificador>CEO</cargoCertificador>
			</grid-5>
			<grid-43>
				<grid-43-iteration>
					<control-45>Apple</control-45>
					<control-46>4</control-46>
				</grid-43-iteration>
				<grid-43-iteration>
					<control-45>None</control-45>
					<control-46>23</control-46>
				</grid-43-iteration>
			</grid-43>
			<section-47>
				<section-47-iteration>
					<grid-6>
						<universidad>UCLA</universidad>
					</grid-6>
					<grid-50>
						<grid-50-iteration>
							<curso>Computing</curso>
						</grid-50-iteration>
						<grid-50-iteration>
							<curso>History</curso>
						</grid-50-iteration>
					</grid-50>
				</section-47-iteration>
				<section-47-iteration>
					<grid-6>
						<universidad>New York</universidad>
					</grid-6>
					<grid-50>
						<grid-50-iteration>
							<curso>Computing History</curso>
						</grid-50-iteration>
						<grid-50-iteration>
							<curso>Laws</curso>
						</grid-50-iteration>
					</grid-50>
				</section-47-iteration>
			</section-47>
		</section-53-iteration>
		<section-53-iteration>
			<grid-5>
				<nombreCertificador>Brad Kuninham</nombreCertificador>
				<cargoCertificador>CIO</cargoCertificador>
			</grid-5>
			<grid-43>
				<grid-43-iteration>
					<control-45>Torch</control-45>
					<control-46>1</control-46>
				</grid-43-iteration>
				<grid-43-iteration>
					<control-45>Lokeed</control-45>
					<control-46>1</control-46>
				</grid-43-iteration>
				<grid-43-iteration>
					<control-45>Bong</control-45>
					<control-46>2</control-46>
				</grid-43-iteration>
			</grid-43>
			<section-47>
				<section-47-iteration>
					<grid-6>
						<universidad>Arizona</universidad>
					</grid-6>
					<grid-50>
						<grid-50-iteration>
							<curso>Computing</curso>
						</grid-50-iteration>
						<grid-50-iteration>
							<curso>Computing Layer</curso>
						</grid-50-iteration>
						<grid-50-iteration>
							<curso>Programming</curso>
						</grid-50-iteration>
					</grid-50>
				</section-47-iteration>
				<section-47-iteration>
					<grid-6>
						<universidad>Oregon</universidad>
					</grid-6>
					<grid-50>
						<grid-50-iteration>
							<curso>Programming 2</curso>
						</grid-50-iteration>
						<grid-50-iteration>
							<curso>Programming 23</curso>
						</grid-50-iteration>
					</grid-50>
				</section-47-iteration>
				<section-47-iteration>
					<grid-6>
						<universidad>Orlando</universidad>
					</grid-6>
					<grid-50>
						<grid-50-iteration>
							<curso>Next</curso>
						</grid-50-iteration>
					</grid-50>
				</section-47-iteration>
			</section-47>
		</section-53-iteration>
		<section-53-iteration>
			<grid-5>
				<nombreCertificador>John McManaman</nombreCertificador>
				<cargoCertificador>CEO/CIO</cargoCertificador>
			</grid-5>
			<grid-43>
				<grid-43-iteration>
					<control-45>CIO</control-45>
					<control-46>2</control-46>
				</grid-43-iteration>
				<grid-43-iteration>
					<control-45>CEO</control-45>
					<control-46>2</control-46>
				</grid-43-iteration>
			</grid-43>
			<section-47>
				<section-47-iteration>
					<grid-6>
						<universidad>Harvard</universidad>
					</grid-6>
					<grid-50>
						<grid-50-iteration>
							<curso>Biology</curso>
						</grid-50-iteration>
						<grid-50-iteration>
							<curso>Computer Programming</curso>
						</grid-50-iteration>
					</grid-50>
				</section-47-iteration>
				<section-47-iteration>
					<grid-6>
						<universidad>UCLA</universidad>
					</grid-6>
					<grid-50>
						<grid-50-iteration>
							<curso>Laws</curso>
						</grid-50-iteration>
					</grid-50>
				</section-47-iteration>
			</section-47>
		</section-53-iteration>
	</section-53>
	<section-81>
		<section-81-iteration>
			<grid-7>
				<denominacionLocal>Montevideo 1</denominacionLocal>
				<direccion>Colonia 87</direccion>
			</grid-7>
			<grid-8>
				<ciudad>Montevideo</ciudad>
				<dpto>montevideo</dpto>
				<tipoConsumidor>tarifa-doble-horario</tipoConsumidor>
				<consumoEnergiaElectrica>1555</consumoEnergiaElectrica>
			</grid-8>
			<grid-9>
				<combustible>16 15 14 13 01 03</combustible>
				<aserrin>15</aserrin>
				<bagazo fr:relevant="false"/>
				<biodiesel>15</biodiesel>
				<bioetanol fr:relevant="false"/>
				<carbon_mineral fr:relevant="false"/>
			</grid-9>
			<grid-10>
				<control-72/>
			</grid-10>
			<grid-83>
				<grid-83-iteration>
					<nombreMedida>GH-58</nombreMedida>
					<usoPrincipal>06</usoPrincipal>
					<energetico_evitado>16</energetico_evitado>
				</grid-83-iteration>
				<grid-83-iteration>
					<nombreMedida>R-87</nombreMedida>
					<usoPrincipal>08</usoPrincipal>
					<energetico_evitado>03</energetico_evitado>
				</grid-83-iteration>
			</grid-83>
		</section-81-iteration>
		<section-81-iteration>
			<grid-10>
				<control-72/>
			</grid-10>
			<grid-9>
				<combustible>01 02 03 04 05</combustible>
				<aserrin>10</aserrin>
				<bagazo>25</bagazo>
				<biodiesel>50</biodiesel>
				<bioetanol>75</bioetanol>
				<carbon_mineral>100</carbon_mineral>
			</grid-9>
			<grid-8>
				<ciudad>San Jose</ciudad>
				<dpto>san-josé</dpto>
				<tipoConsumidor>gc1</tipoConsumidor>
				<consumoEnergiaElectrica>1580</consumoEnergiaElectrica>
			</grid-8>
			<grid-7>
				<denominacionLocal>Montevideo 2</denominacionLocal>
				<direccion>18 de Julio 34</direccion>
			</grid-7>
			<grid-83>
				<grid-83-iteration>
					<nombreMedida>WEFG-458</nombreMedida>
					<usoPrincipal>03</usoPrincipal>
					<energetico_evitado>12</energetico_evitado>
				</grid-83-iteration>
				<grid-83-iteration>
					<nombreMedida>TEE-988</nombreMedida>
					<usoPrincipal>04</usoPrincipal>
					<energetico_evitado>05</energetico_evitado>
				</grid-83-iteration>
			</grid-83>
		</section-81-iteration>
	</section-81>
</form>'