all type conditions
formInstance_ue_allTypes_name: nameString amount: amountString time: timeString timeStamp: timeStampString date: dateString bool: boolString

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>Fs8Ydj3nA-CAqeWP</s>
			<k>2aV_7OtHlDSIAnf2</k>
			<uuid>e4fb58c4-c7f6-441c-aa62-2a0677f74265</uuid>
			<oop>11662536449</oop>
			<assignmentOop>11662543105</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>alberto</username>
			<rol>[manager][approver][runner][vendor][data-entry-1]</rol>
			<processId>2932095122</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<name>',nameString,'</name>
			<amount>',amountString,'</amount>
			<time>',timeString,'</time>
			<timeStamp>',timeStampString,'</timeStamp>
			<date>',dateString,'</date>
			<boolean>',boolString,'</boolean>
		</grid-3>
	</section-12>
</form>'