issue 369
formInstance_agesic_manual_form_issue_369

	^'<?xml version="1.0" encoding="UTF-8"?>
			<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<section-1>
		<grid-1>
			<description>Factura Setiembre Sony</description>
		</grid-1>
	</section-1>
	<section-2>
		<grid-3>
			<grid-3-iteration>
				<type>baked-goods</type>
				<date>2020-09-28</date>
				<quantity>5</quantity>
				<price>250.36</price>
				<available>true</available>
				<currency>usd</currency>
			</grid-3-iteration>
		</grid-3>
	</section-2>
</form>'