all gateways process
formInstance_ue_task_1

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>cINRJyDvEbPhhR86</s>
			<k>n8pB1SZqRzfmBbZd</k>
			<uuid>533ff89f-db88-408c-9339-9ecda41c5413</uuid>
			<oop>8883267073</oop>
			<assignmentOop>8883273217</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>alberto</username>
			<rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
			<formId>nil</formId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<taskOnevalue>98</taskOnevalue>
		</grid-3>
	</section-12>
</form>'