enter data recursive
formInstance_ue_approve_data_recursive_no

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>Y-Zzxf08LsHDZgVG</s>
			<k>tDxvh7wElNek2gSF</k>
			<uuid>afe6c52b-12c9-4dd6-89fa-c7ed78d5f61d</uuid>
			<oop>8297397505</oop>
			<assignmentOop>8297404161</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>mario</username>
			<rol>[data-entry-3]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<approved>no</approved>
		</grid-3>
	</section-12>
</form>'