all gateways process
formInstance_ue_task_7

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>cINRJyDvEbPhhR86</s>
			<k>9-9VU_EYs-K29GGq</k>
			<uuid>4dcff0a6-7f0a-4e00-8a30-bd8dd0e4f558</uuid>
			<oop>8910727425</oop>
			<assignmentOop>8910729729</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>alberto</username>
			<rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3/>
	</section-12>
</form>'