all gateways process
formInstance_ue_task_3

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>cINRJyDvEbPhhR86</s>
			<k>B4rM8Olob2iQhP6e</k>
			<uuid>d58439a2-875f-4acf-a3d2-9e7cc04a35df</uuid>
			<oop>8890691329</oop>
			<assignmentOop>8890693889</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>alberto</username>
			<rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<taskThreeOption>30</taskThreeOption>
		</grid-3>
	</section-12>
</form>'