visa process
formInstance_ue_citizen_appliance_random_country

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>ApGa9W3Ul4nHOlSi</s>
			<k>JlF4NwfVyNrX5GDt</k>
			<uuid>3cf02657-5e73-4375-b76c-528bbb09ca59</uuid>
			<oop>7211706369</oop>
			<assignmentOop>7211978241</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>andrew vo</username>
			<rol>[visa officer]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<citizenName>Paulo</citizenName>
			<citizenSurname>Cohelo</citizenSurname>
			<citizenEmail>brunobb@dd.com</citizenEmail>
			<citizenPhone>654792</citizenPhone>
			<citizenBirth>1970-03-18</citizenBirth>
			<gender>male</gender>
			<originCountry>', self getRandomCountry,'</originCountry>
			<citizenId>65874521</citizenId>
		</grid-3>
	</section-12>
</form>'