issue 122
formInstance_ue_issue122

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
	<section-1>
		<name>bruno</name>
	</section-1>
	<section-2>
		<street/>
		<number/>
		<subNumber/>
		<section-2-iteration>
			<grid-2>
				<street>chana</street>
				<number>1938</number>
				<subNumber>101</subNumber>
			</grid-2>
		</section-2-iteration>
		<section-2-iteration>
			<grid-2>
				<street>chana</street>
				<number>555</number>
				<subNumber>4</subNumber>
			</grid-2>
		</section-2-iteration>
	</section-2>
</form>'