other
style
 ^ '
#orbeon-section{
	margin-left: 150px;
}
#orbeon-definitions {
	margin-left: 100px;
	margin-top: -240px;
}
#orbeon-instances {
	margin-left: 100px;
}
.reportColumn 
{
	font-family:"Times New Roman", Times, serif;
	font-size: 20px;
	font-color: red;
	}
 body{
     background-color: rgb(223, 228, 206);
 }
table {
	display: table;
	border-collapse: separate;
	border-spacing: 2px;
	border-color: red;
}
td, th {
	display: table-cell;
	vertical-align: inherit;
	border-style: groove;
}
#sidebar {
	height: 400px;
	width: 150px;
	position: fixed;
	background-color: lightgray;
	}
#tabs-section {
	margin-top: 70px;
	margin-left: 150px;
}
#header{
     width: 100%;
     height: 40px;
     padding-left: 5px;
     background-color: #d7eeee;
 }

#content{
     font-family: arial;
     text-align: justify;
     margin-left: 150px;
     margin-right: 5px;
     padding-left: 5px;
     padding-right: 5px;
     padding-top: 5px;
     padding-bottom: 5px;
     background-color: silver;
 }

#tabs{
    list-style-type: none;
	margin-left: -40px;
 }

#tabs li{
     display: inline;
 }

#tabs li a{
     text-align: center;
     width: 80px;
     height: 25px;
     color: #000;
     background-color: #d7eeee;
     margin: 1px;
     padding: 0.5em;
     font-size: 30px;
     text-decoration: none
; }

#tabs li a:hover{
     /*font-weight: bold; */
     background-color: lightgreen;
 }
 '