other
style
 ^ '
 body{
     background-color: #aeeeee;
 }
#header{
     width: 100%;
     height: 40px;
     padding-left: 5px;
     background-color: #d7eeee;
 }

#content{
     font-family: arial;
     text-align: justify;
     margin-left: 5px;
     margin-right: 5px;
     padding-left: 5px;
     padding-right: 5px;
     padding-top: 5px;
     padding-bottom: 5px;
     background-color: #f7eeee;
 }

#tabs{
     list-style-type: none;
 }

#tabs li{
     display: inline;
 }

#tabs li a{
     text-align: center;
     width: 100%;
     height: 25px;
     color: #000;
     background-color: #d7eeee;
     margin: 0.5em;
     padding: 0.5em;
     font-size: 12px;
     text-decoration: none
; }

#tabs li a:hover{
     font-weight: bold;
 }
 '