all types
formInstance_agesic_test_all_types_2

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<section-1>
		<section-1-iteration>
			<grid-1>
				<name>Bruno</name>
				<surname>Buzzi Brassesco</surname>
				<phone>4444444445</phone>
				<mail>b@b.st</mail>
				<boolean>true</boolean>
			</grid-1>
			<section-7>
				<grid-2>
					<control-8/>
					<mobile>0995689</mobile>
				</grid-2>
				<grid-10>
					<grid-10-iteration>
						<moneySubject>1</moneySubject>
						<quantity>12</quantity>
						<currency>45.36</currency>
					</grid-10-iteration>
					<grid-10-iteration>
						<quantity>24</quantity>
						<currency>69</currency>
						<moneySubject>2</moneySubject>
					</grid-10-iteration>
					<grid-10-iteration>
						<quantity>48</quantity>
						<currency>12045</currency>
						<moneySubject>3</moneySubject>
					</grid-10-iteration>
				</grid-10>
			</section-7>
		</section-1-iteration>
	</section-1>
	<section-14>
		<grid-3>
			<date1>2021-04-09</date1>
			<dateTime>2021-04-09T17:21:30</dateTime>
			<date2>2021-04-09</date2>
			<date3>2021-04-09</date3>
			<time>17:21:30.116-04:00</time>
			<details>Some details here</details>
			<type>2</type>
		</grid-3>
		<grid-19>
			<grid-19-iteration>
				<options>1</options>
				<otherOptions>2</otherOptions>
			</grid-19-iteration>
			<grid-19-iteration>
				<options>2</options>
				<otherOptions>3</otherOptions>
			</grid-19-iteration>
		</grid-19>
		<section-24>
			<grid-4>
				<formatedText>&lt;div&gt;&lt;strong&gt;This is rich text editor&lt;/strong&gt;&lt;/div&gt;&lt;ul&gt;&lt;li&gt;&lt;strong&gt;1&lt;/strong&gt;&lt;/li&gt;&lt;li&gt;&lt;strong&gt;2&lt;/strong&gt;&lt;/li&gt;&lt;li&gt;&lt;strong&gt;3&lt;/strong&gt;&lt;/li&gt;&lt;li&gt;&lt;strong&gt;4&lt;/strong&gt;&lt;/li&gt;&lt;/ul&gt;&lt;ol&gt;&lt;li&gt;&lt;strong&gt;dd&lt;/strong&gt;&lt;/li&gt;&lt;li&gt;&amp;nbsp;&lt;/li&gt;&lt;/ol&gt;&lt;div id="sconnect-is-installed" style="display: none;"&gt;2.11.0.0&lt;/div&gt;</formatedText>
				<fileAttachment filename="TestCase.odt" mediatype="application/vnd.oasis.opendocument.text" size="9752">/fr/service/persistence/crud/agesic/test/form/6f24ab215fbd0bba5df2ca3eef4d4b257eb28599.bin</fileAttachment>
				<imageAttachment filename="foto.JPG" mediatype="image/jpeg" size="30799">/fr/service/persistence/crud/agesic/test/form/13b8243012ae9f164239ab4dce6ebce5bc74a4d4.bin</imageAttachment>
				<imageAnnotation>
					<image filename="" mediatype="" size=""/>
					<annotation/>
				</imageAnnotation>
				<autocomplete label=""/>
			</grid-4>
		</section-24>
	</section-14>
</form>'