visa process
formInstance_ue_check_debts_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>uIC70JOwGjKpA-iq</s>
			<k>SOAqQF9Ya1PdWaHz</k>
			<uuid>2216c48c-6491-48f5-87a6-390c2616f1e4</uuid>
			<oop>7468812801</oop>
			<assignmentOop>7468814849</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>andrew do</username>
			<rol>[debts officer]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<citizenName>Bruno</citizenName>
			<citizenSurname>Buzzi Brassesco</citizenSurname>
			<originCountry>uruguay</originCountry>
			<citizenId>37673595</citizenId>
		</grid-3>
	</section-12>
	<section-16>
		<grid-4>
			<debtsDetails>&lt;div&gt;1 loan debt - ok with payments - value $1.000.000 - to pay: $300.000&lt;/div&gt;</debtsDetails>
		</grid-4>
	</section-16>
</form>'