visa process
formInstance_ue_emit_visa_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>GzYda_4xduX04QCG</s>
			<k>PL3oy6zcdjh3bVmw</k>
			<uuid>9899344c-5602-4c00-afb9-0f4dd81dd1cb</uuid>
			<oop>7507942401</oop>
			<assignmentOop>7507943681</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>andrew vm</username>
			<rol>[visa manager]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<citizenName>Ceci</citizenName>
			<citizenSurname>Keu</citizenSurname>
			<citizenEmail>brunobb@dd.com</citizenEmail>
			<citizenPhone>999106087</citizenPhone>
			<citizenBirth>1980-03-18</citizenBirth>
			<gender>female</gender>
			<originCountry>brazil</originCountry>
			<citizenId>37673595</citizenId>
		</grid-3>
	</section-12>
	<section-20>
		<grid-4>
			<visa>/fr/service/persistence/crud/ue/emit-visa/form/d8086109a226179fe15ecc4c4e9d1eab2f60db8e.bin</visa>
		</grid-4>
	</section-20>
</form>'