simple registratio process
formInstance_st_simple_registration

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<section-12>
		<grid-1>
			<registrationName>Juan</registrationName>
			<registrationSurname>Perez</registrationSurname>
			<originCountry>argentina</originCountry>
			<registrationId>649874</registrationId>
		</grid-1>
	</section-12>
	<section-16>
		<grid-2>
			<registrationDetails>&lt;div&gt;&lt;strong&gt;mmmh&lt;/strong&gt;&lt;/div&gt;</registrationDetails>
		</grid-2>
	</section-16>
</form>'