issue 389
formInstance_gs_test_library_issue_389
	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<section-2>
		<section-2-iteration>
			<grid-1>
				<name>bruno</name>
				<surname>buzzi</surname>
			</grid-1>
		</section-2-iteration>
		<section-2-iteration>
			<grid-1>
				<name>franco</name>
				<surname>buzzi</surname>
			</grid-1>
		</section-2-iteration>
		<section-2-iteration>
			<grid-1>
				<name>cecilia</name>
				<surname>keuroglian</surname>
			</grid-1>
		</section-2-iteration>
	</section-2>
	<section-1>
		<section-2-iteration fr:relevant="false">
			<grid-2>
				<number>123456</number>
			</grid-2>
		</section-2-iteration>
	</section-1>
	<section-3>
		<section-3-iteration>
			<grid-5>
				<country>Uruguay</country>
			</grid-5>
			<section-4>
				<grid-4>
					<grid-4-iteration>
						<city>Montevideo</city>
					</grid-4-iteration>
					<grid-4-iteration>
						<city>Punta del Este</city>
					</grid-4-iteration>
				</grid-4>
			</section-4>
		</section-3-iteration>
		<section-3-iteration>
			<grid-5>
				<country>Argentina</country>
			</grid-5>
			<section-4>
				<grid-4>
					<grid-4-iteration>
						<city>Buenos Aires</city>
					</grid-4-iteration>
					<grid-4-iteration>
						<city>La Plata</city>
					</grid-4-iteration>
				</grid-4>
			</section-4>
		</section-3-iteration>
	</section-3>
</form>'