all type conditions
formInstance_ue_all_field_types_amount_exit

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
                    <internal-section>
					  <grid-1>
                        <s>Fs8Ydj3nA-CAqeWP</s>
                        <k>2aV_7OtHlDSIAnf2</k>
                        <uuid>e4fb58c4-c7f6-441c-aa62-2a0677f74265</uuid>
                        <oop>11662536449</oop>
                        <assignmentOop>11662543105</assignmentOop>
					  </grid-1>
                    </internal-section>
                    <section-11>
					  <grid-2>
                        <username>alberto</username>
                        <rol>[manager][approver][runner][vendor][data-entry-1]</rol>
                        <processId>2932095122</processId>
					  </grid-2>
                    </section-11>
                    <section-12>
					  <grid-3>
                        <name>bruno</name>
                        <amount>10</amount>
                        <time>08:00:00</time>
                        <timeStamp>2016-04-11T10:00:00</timeStamp>
                        <date>2016-04-11</date>
                        <boolean>true</boolean>
					  </grid-3>
                    </section-12>
                </form>'