visa process
formInstance_ue_check_applicant_record_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>LvyCHXZ8NXzlaNBp</s>
			<k>hraR-tClA1bw3EC1</k>
			<uuid>faacb4b3-2026-4caf-a36f-8004701ee5b7</uuid>
			<oop>7387612161</oop>
			<assignmentOop>7386091009</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>andrew vc</username>
			<rol>[visa checker]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<citizenName>Bruno</citizenName>
			<citizenSurname>Buzzi Brassesco</citizenSurname>
			<originCountry>uruguay</originCountry>
			<citizenId>37673595</citizenId>
		</grid-3>
	</section-12>
	<section-16>
		<grid-4>
			<checkApplicantRecord/>
		</grid-4>
	</section-16>
</form>'