visa process
formInstance_ue_financial_report_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>0HDqhuoi9HSrnFeW</s>
			<k>EX4X_OSddcqOThxp</k>
			<uuid>cb3330dd-fef3-46fc-b5b9-d0907eedd7d4</uuid>
			<oop>7478802433</oop>
			<assignmentOop>7478803713</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>andrew fo</username>
			<rol>[finance officer]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<citizenName>Bruno</citizenName>
			<citizenSurname>Buzzi Brassesco</citizenSurname>
			<originCountry>uruguay</originCountry>
			<citizenId>37673595</citizenId>
		</grid-3>
	</section-12>
	<section-16>
		<grid-17>
			<grid-17-iteration>
				<assetType>debt</assetType>
				<assetValue>300000</assetValue>
			</grid-17-iteration>
			<grid-17-iteration>
				<assetType>bank-accout</assetType>
				<assetValue>600000</assetValue>
			</grid-17-iteration>
			<grid-17-iteration>
				<assetType>bank-accout</assetType>
				<assetValue>50000</assetValue>
			</grid-17-iteration>
			<grid-17-iteration>
				<assetType>bank-accout</assetType>
				<assetValue>900000</assetValue>
			</grid-17-iteration>
			<grid-17-iteration>
				<assetType>stock-shares</assetType>
				<assetValue>1000000</assetValue>
			</grid-17-iteration>
		</grid-17>
	</section-16>
</form>'