all gateways process
formInstance_ue_task_2_1

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>cINRJyDvEbPhhR86</s>
			<k>m0z0z1OzmTG9jjb-</k>
			<uuid>e7f725df-81dd-466d-a5a3-3a1dd610d563</uuid>
			<oop>8890691585</oop>
			<assignmentOop>8890694145</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>alberto</username>
			<rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<taskTwoOption>1</taskTwoOption>
		</grid-3>
	</section-12>
</form>'