all gateways process
formInstance_ue_task_4

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>cINRJyDvEbPhhR86</s>
			<k>KTeq2qL3dlcx78By</k>
			<uuid>f08f07c1-0d3d-4cb9-8681-82a1accc09cd</uuid>
			<oop>8863938049</oop>
			<assignmentOop>8863940353</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>alberto</username>
			<rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<taskFourEnable>true</taskFourEnable>
		</grid-3>
	</section-12>
</form>'