test 2
formInstance_agesic_test_2

	^ '<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<section-normal>
		<grid-1>
			<name>Bruno</name>
			<surname>Buzzi</surname>
		</grid-1>
	</section-normal>
	<section-repeatable>
		<section-repeatable-iteration>
			<grid-2>
				<phones>4087536</phones>
			</grid-2>
			<section-sub>
				<grid-3>
					<address>chana</address>
				</grid-3>
			</section-sub>
		</section-repeatable-iteration>
		<section-repeatable-iteration>
			<grid-2>
				<phones>0999</phones>
			</grid-2>
			<section-sub>
				<grid-3>
					<address>Libre</address>
				</grid-3>
			</section-sub>
		</section-repeatable-iteration>
		<section-repeatable-iteration>
			<grid-2>
				<phones>712</phones>
			</grid-2>
			<section-sub>
				<grid-3>
					<address>pocitos</address>
				</grid-3>
			</section-sub>
		</section-repeatable-iteration>
	</section-repeatable>
</form>'