visa process
formInstance_ue_check_basic_data_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="2019.1.0">
	<internal-section>
		<grid-1>
			<s>ApGa9W3Ul4nHOlSi</s>
			<k>y0XV1CcVU7W38FRU</k>
			<uuid>7d3fa7fd-135a-44eb-bd85-16fd8e27db87</uuid>
			<oop>7329584385</oop>
			<assignmentOop>7329585665</assignmentOop>
		</grid-1>
	</internal-section>
	<section-11>
		<grid-2>
			<username>andrew vo</username>
			<rol>[visa officer]</rol>
			<processId>nil</processId>
		</grid-2>
	</section-11>
	<section-12>
		<grid-3>
			<citizenName>Bruno</citizenName>
			<citizenSurname>Buzzi Brassesco</citizenSurname>
			<citizenEmail>brunobb@dd.com</citizenEmail>
			<citizenPhone>999106087</citizenPhone>
			<citizenBirth>1980-03-18</citizenBirth>
			<gender>male</gender>
			<originCountry>uruguay</originCountry>
			<citizenId>37673595</citizenId>
		</grid-3>
	</section-12>
	<section-20>
		<grid-4>
			<checkResult>passed</checkResult>
		</grid-4>
	</section-20>
</form>'