library forms
form_library_composed_form

	^'<?xml version="1.0" encoding="UTF-8"?>
<form>
	<section-8>
		<s>s1</s>
		<k>k1</k>
		<uuid>u1</uuid>
		<oop>op1</oop>
		<assignmentOop>op2</assignmentOop>
	</section-8>
	<section-14>
		<username>bruno</username>
		<rol>admin</rol>
		<processId>12</processId>
	</section-14>
	<section-name>
		<name>john</name>
		<surname>conor</surname>
	</section-name>
	<section-address>
		<street>av end</street>
		<number>123</number>
		<subNumber>543</subNumber>
	</section-address>
</form>'