all gateways process
form_task3

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>cINRJyDvEbPhhR86</s>
                        <k>B4rM8Olob2iQhP6e</k>
                        <uuid>d58439a2-875f-4acf-a3d2-9e7cc04a35df</uuid>
                        <oop>8890691329</oop>
                        <assignmentOop>8890693889</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>
                        <taskThreeOption>30</taskThreeOption>
                    </section-12>
                </form>'