visa process
form_citizen_appliance_1

^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>ApGa9W3Ul4nHOlSi</s>
                        <k>JlF4NwfVyNrX5GDt</k>
                        <uuid>3cf02657-5e73-4375-b76c-528bbb09ca59</uuid>
                        <oop>7211706369</oop>
                        <assignmentOop>7211978241</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>andrew vo</username>
                        <rol>[visa officer]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>
                        <citizenName>Bruno</citizenName>
                        <citizenSurname>Buzzi Brassesco</citizenSurname>
                        <citizenEmail>brunobb@dd.com</citizenEmail>
                        <citizenPhone>999106087</citizenPhone>
                        <citizenBirth>1980-03-18</citizenBirth>
                        <gender>male</gender>
                        <originCountry>uruguay</originCountry>
                        <citizenId>37673595</citizenId>
                    </section-12>
                </form>'