all gateways process
form_task4

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>cINRJyDvEbPhhR86</s>
                        <k>KTeq2qL3dlcx78By</k>
                        <uuid>f08f07c1-0d3d-4cb9-8681-82a1accc09cd</uuid>
                        <oop>8863938049</oop>
                        <assignmentOop>8863940353</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12><taskFourEnable>true</taskFourEnable>                    
                    </section-12>
                </form>'