other
xmlQueryString

	^ '<?xml version="1.0" encoding="UTF-8"?><search xmlns:xbl="http://www.w3.org/ns/xbl" xmlns:xxf="http://orbeon.org/oxf/xml/xforms" xmlns:xxi="http://orbeon.org/oxf/xml/xinclude" xmlns:saxon="http://saxon.sf.net/" xmlns:fr="http://orbeon.org/oxf/xml/form-runner" xmlns:xf="http://www.w3.org/2002/xforms" xmlns:xh="http://www.w3.org/1999/xhtml" xmlns:p="http://www.orbeon.com/oxf/pipeline" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:xi="http://www.w3.org/2001/XInclude" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:frf="java:org.orbeon.oxf.fr.FormRunner">
                    <query/><query name="name" path="section-12/name" type="xs:string" control="input" search-field="true" summary-field="true" match="substring" html-label="false"/><query name="amount" path="section-12/amount" type="xs:positiveInteger" control="input" search-field="true" summary-field="true" match="substring" html-label="false"/>
                    <page-size>10</page-size>
                    <page-number>1</page-number>
                    <lang>en</lang>
                </search>'