other
style
 ^ '
a img {
	padding-left: 4px;
	padding-top: 4px;
}
#banner {
	margin-top: -8px;
}
.batch {
	text-align: center;
}
body{
     background-color: silver;
 }
#close a {
	margin-left: 120px;
}
#content{
     font-family: arial;
     text-align: justify;
     margin-left: 180px;
     margin-right: 5px;
     padding-left: 5px;
     padding-right: 5px;
     padding-top: 5px;
     padding-bottom: 5px;
     background-color: silver;
 }
#form-user-panel {
	margin-top: 100px;
	margin-left: 200px;
	background-color: beige;
	border-style: inset;
	border-radius: 15px;
	border-width: 2px;
	width: 950px;
	margin-bottom: 20px;
}
#form-user-panel form {
	width: 950px;
}
#form-user-panel form fieldset { 
	border: 0;
}
#form-user-panel form fieldset input { 
	border-radius: 10px;
	background-color: lavender;
	margin-right: 5px;
}
#form-user-panel form fieldset select { 
	border-radius: 10px;
	background-color: lavender;
	margin-right: 5px;
}
#form-user-panel form fieldset label { 
	margin-right: 5px;
}
#header{
     width: 100%;
     height: 40px;
     padding-left: 5px;
     background-color: #d7eeee;
 }
.hidden {
	position: absolute;
	left: -10000px;
	top: auto;
	width: 1px;
	height: 1px;
	overflow: hidden;
}
#login-mode-configuration { 
	display: flex;
	margin-left: 200px;
	margin-top: 100px;
}
#login-mode-configuration form {
	width: 390px;
	margin: 10px auto 10px 250px;
}
#login-mode-configuration form fieldset { 
	border-radius: 10px;
	border-style: inset;
	background-color: rgb(163, 187, 164);
}
#login-mode-configuration form fieldset input[type="text"]{ 
	border-radius: 10px;
	border-style: inset;
	width: 350px;
	margin-bottom: 10px;
}
#login-mode-configuration form fieldset input[type="submit"]{ 
	border-radius: 10px;
	width: 150px;
	border-right: 10px;
}
#login-mode-configuration form fieldset label { 
	display: block;
}
#login-mode-configuration form fieldset select { 
	border-radius: 10px;
	border-style: inset;
	display: block;
	width: 350px;
	margin-bottom: 10px;
}
.marginLeft5px {
	margin-left: 5px;
}
.marginLeft10px {
	margin-left: 10px;
}
.marginLeft15px {
	margin-left: 15px;
}
#manager-options {
	/*margin-left: 200px; */
}
#manager-option {
	display: inline-block;
	margin-left: 5px;
}
.reportColumn 
{
	font-family:"Times New Roman", Times, serif;
	font-size: 20px;
	/*border-radius: 6px; */
	}
#rols-list {
	display: inline-block;
	margin-left: 50px;
	float: left;
	width: 200px;
}
#rols-list input.submit {
	width: 120px;
	height: 30px;
	font-size: medium;
	background-color: lavender;
	border-radius: 12px;
	margin-top: 5px;
}
#rol-type-list {
	display: inline-block;
}
#rol-type-list fieldset {
	border-radius: 15px;
	background-color: beige;
}
#rol-type-list legend {
	border-radius: 15px;
	background-color: beige;
}
#rol-type-list label {
	margin-right: 10px;
}
#rol-type-list select {
	margin-right: 10px;
}
#rol-type-list input.submit {
	width: 120px;
	height: 30px;
	font-size: medium;
	background-color: lavender;
	border-radius: 12px;
}
#server-configuration { 
	display: flex;
	margin-left: 200px;
	margin-top: 100px;
}
#server-configuration form {
	width: 390px;
	margin: 10px auto 10px 250px;
}
#server-configuration form fieldset { 
	border-radius: 10px;
	border-style: inset;
	background-color: rgb(163, 187, 164);
}
#server-configuration form fieldset input[type="text"]{ 
	border-radius: 10px;
	border-style: inset;
	width: 350px;
	margin-bottom: 10px;
}
#server-configuration form fieldset input[type="submit"]{ 
	border-radius: 10px;
	width: 150px;
	border-right: 10px;
}
#server-configuration form fieldset label { 
	display: block;
}
#server-configuration form fieldset select { 
	border-radius: 10px;
	border-style: inset;
	display: block;
	width: 350px;
	margin-bottom: 10px;
}
#sidebar {
	border-radius: 25px;
	height: 400px;
	width: 180px;
	position: absolute;
	text-align: center;
	background-color: gray;
	background-repeat: repeat-x;
	border-style: ridge;
	margin-left: -4px;
	}
#tabs{
    list-style-type: none;
	margin-left: -40px;
 }

#tabs li{
     display: inline;
 }

#tabs li a{
     text-align: center;
	 border-radius: 20px;
     width: 80px;
     height: 25px;
     color: #000;
     background-color: #EEEEEE;
     margin: 1px;
     padding: 0.5em;
     font-size: 30px;
     text-decoration: none; 
}
#tabs li a:hover{
     background-color: gray; 
 } 
table {
	display: table;
	border-collapse: separate;
	border-spacing: 2px;
	border-color: red;
}
th, td {
	display: table-cell;
	vertical-align: inherit;
	border-bottom: white;
	border-width: 1px;
	border-style: inset;
	width: 1px;
	white-space: nowrap;
}
#top-bar { 
	padding-right: 20px;
	border-radius: 20px;
	height: 30px;
	text-align: right;
	float: right;
	padding-left: 10px;
	background-color: beige;
}
.top-toolbar-menu { /* menu with 1 tool link */
	margin-right: 10px;
	/* margin-bottom: 10px; */
	/* padding-right: 2px; */
	/*height: 75px; */
	float: left;
	border-radius: 15px;
	background-color: beige;
	padding-right: 9px;
	padding-top: 7px;
	padding-left: 1px;
}
.top-toolbar-menu-x1 { /* menu with 1 tool link */
	width: 72px;
}
.top-toolbar-menu-x2 { /* menu with 2 tool link */
	width: 160px;
}
.top-toolbar-menu-x3 { /* menu with 3 tool link */
	width: 215px;
}
.top-toolbar-menu-x4 { /* menu with 4 tool link */
	width: 288px;
}
.top-toolbar-menu-selected-item {
	background-color: silver;
	border-style: inset;
	border-width: 1px;
	border-radius: 10px;
}
#tabs-section {
	margin-top: 70px; 
	margin-left: 180px;
	 padding-left: 5px;
} 
#user-password-widget {
	margin-top: 90px;
	width: 390px;
	margin-top: 90px;
	margin-left: 200px;
}
#user-password-widget form fieldset { 
	border-radius: 10px;
	border-style: inset;
	background-color: rgb(163, 187, 164);
}
#user-password-widget form fieldset input[type="text"]{ 
	border-radius: 10px;
	border-style: inset;
	width: 350px;
	margin-bottom: 10px;
}
#user-password-widget form fieldset input[type="submit"]{ 
	border-radius: 10px;
	width: 150px;
	border-right: 10px;
}
#user-password-widget form fieldset label { 
	display: block;
}
#user-password-widget form fieldset select { 
	border-radius: 10px;
	border-style: inset;
	display: block;
	width: 350px;
	margin-bottom: 10px;
}
#user-rol-area {
	margin-left: 200px;
}
#user-rol-area h2 {
	margin-top: 30px;
}
#user-list {
	float: left;
	display: inline-block;
}
#user-list form table {
	width: 300px;
	text-align: center;
}
#user-list input.submit {
	width: 120px;
	height: 30px;
	font-size: medium;
	background-color: lavender;
	border-radius: 12px;
	margin-top: 5px;
}
'