orbeon fields
orbeonCollectableFieldsTags
	"Answer a collection of Orbeon tags designed to represent components in a XForms definition.
	At render time Orbeon transform each of these tags to an HMTL tag."

	^#('xf:input' 'xf:select1' 'xf:textarea' 'fr:number' 'xf:select' 'fr:dropdown-date' 'xf:secret' 'fr:tinymce' 'us:phone' 'fr:currency' 'fr:fields-date' 'fr:date-picker' 'fr:box-select' 'fr:databound-select1' 'fr:autocomplete' 'xf:output' 'fr:image-attachment' 'fr:attachment' 'fr:wpaint' 'fr:dropdown-select1' 'fr:us-phone')