event based gateway
form_house_purchase_application_1

^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>GzYda_4xduX04QCG</s>
                        <k>JcZbP5haZDlS3aGl</k>
                        <uuid>94398220-aaac-4232-bf8e-38715c8217c4</uuid>
                        <oop>7496192001</oop>
                        <assignmentOop>7496195585</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>andrew vm</username>
                        <rol>[visa manager]</rol>
                        <processId>nil</processId>
                    </section-11>
                    <section-20>
                        <personID>123456789</personID>
                        <name>Bruno</name>
                        <surname>Buzzi Brassesco</surname>
                        <state>Oregon</state>
                        <city>Beaverton</city>
                        <address>45625 SW Green Park</address>
                        <price>180000</price>
                        <tax>30000</tax>
                    </section-20>
                </form>'