visa process
form_check_applicant_record_1

^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>LvyCHXZ8NXzlaNBp</s>
                        <k>hraR-tClA1bw3EC1</k>
                        <uuid>faacb4b3-2026-4caf-a36f-8004701ee5b7</uuid>
                        <oop>7387612161</oop>
                        <assignmentOop>7386091009</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>andrew vc</username>
                        <rol>[visa checker]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>
                        <citizenName>Bruno</citizenName>
                        <citizenSurname>Buzzi Brassesco</citizenSurname>
                        <originCountry>uruguay</originCountry>
                        <citizenId>37673595</citizenId>
                    </section-12>
                    <section-16><checkApplicantRecord/>                     
                    </section-16>
                </form>'