simple registration process
form_registration_approval_1

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>Z-TDf9jjx6pSXqt9</s>
                        <k>LKOKSshYqrljrnOQ</k>
                        <uuid>8c9d30cf-8bd2-4de2-9c33-132038911f84</uuid>
                        <oop>7687898113</oop>
                        <assignmentOop>7687910401</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[Vendor][rrhh][ing civil][admin][approver]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>
                        <result>approved</result>
                    </section-12>
                </form>'