miem
form_alta_representacion_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
	<internal-section>
		<s/>
		<k/>
		<uuid/>
		<oop/>
		<assignmentOop/>
	</internal-section>
	<section-11>
		<username/>
		<rol/>
		<processId/>
	</section-11>
	<section-12>
		<repNombreUsuario>juan@MIEM</repNombreUsuario>
		<repNombre>Pedro</repNombre>
		<repApellido>Pereira Perez</repApellido>
		<repCargo>Operario Web</repCargo>
		<repTelefono>741 25 89</repTelefono>
		<repMail>pedro@gmail.com</repMail>
		<repTipo>total</repTipo>
	</section-12>
	<section-18>
		<repEsTotal>true</repEsTotal>
	</section-18>
</form>'