miem
form_resolver_postulacion

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
	<internal-section>
		<s>T1i3YUpC2RYOU4fX</s>
		<k>-bnduD8L2VGdvryj</k>
		<uuid>eb486b16-b4bf-4b80-bc83-6a6356552ec3</uuid>
		<oop>9846419713</oop>
		<assignmentOop>9846421505</assignmentOop>
	</internal-section>
	<section-11>
		<username>pedro@MIEM</username>
		<rol>[Operador]</rol>
		<processId>2982381295</processId>
	</section-11>
	<section-1>
		<necesitaAclaraciones>false</necesitaAclaraciones>
		<aprobada>true</aprobada>
		<resolucionComentarios/>
	</section-1>
</form>'