all gateways process
form_task2

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>cINRJyDvEbPhhR86</s>
                        <k>m0z0z1OzmTG9jjb-</k>
                        <uuid>e7f725df-81dd-466d-a5a3-3a1dd610d563</uuid>
                        <oop>8890691585</oop>
                        <assignmentOop>8890694145</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>
                        <taskTwoOption>3</taskTwoOption>
                    </section-12>
                </form>'