event based gateway
form_cancel_purchase

^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>GzYda_4xduX04QCG</s>
                        <k>JcZbP5haZDlS3aGl</k>
                        <uuid>94398220-aaac-4232-bf8e-38715c8217c4</uuid>
                        <oop>7496192001</oop>
                        <assignmentOop>7496195585</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>andrew vm</username>
                        <rol>[visa manager]</rol>
                        <processId>nil</processId>
                    </section-11>
                    <section-20>
                        <cancelDetails>Loan Not Approved</cancelDetails>
                    </section-20>
                </form>'