all gateways process
form_task7

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>cINRJyDvEbPhhR86</s>
                        <k>9-9VU_EYs-K29GGq</k>
                        <uuid>4dcff0a6-7f0a-4e00-8a30-bd8dd0e4f558</uuid>
                        <oop>8910727425</oop>
                        <assignmentOop>8910729729</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>              
                    </section-12>
                </form>'