all gateways process
form_task5_1

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>cINRJyDvEbPhhR86</s>
                        <k>B8Deq0zWwNZ2FmhH</k>
                        <uuid>9011c8da-b21f-428d-96b2-0691974f4152</uuid>
                        <oop>8905932033</oop>
                        <assignmentOop>8905934337</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12><taskFiveDate>2015-04-08</taskFiveDate>                       
                    </section-12>
                </form>'