issue369
form_issue369_v1

	^'<?xml version="1.0" encoding="UTF-8"?><form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
                    <section-1>
                        <description>Factura Setiembre Sony</description>
                    </section-1>
                    <section-2>
                        <grid-3>
                                <type>baked-goods</type>
                                <date>2020-09-28</date>
                                <quantity>5</quantity>
                                <price>250.36</price>
                                <available>true</available>
                                <currency>usd</currency>
                            </grid-3>
                    </section-2>
                </form>'