miem
form_alta_empresa_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
	<internal-section>
		<s/>
		<k/>
		<uuid/>
		<oop/>
		<assignmentOop/>
	</internal-section>
	<section-11>
		<username/>
		<rol/>
		<processId/>
	</section-11>
	<section-12>
		<empRazonSocial>Industrias Kaplan</empRazonSocial>
		<empRut>7897 987 654 654</empRut>
		<empCIIU>21</empCIIU>
		<empTelefono>458 858 696</empTelefono>
		<empFax>478 545 878</empFax>
		<empDireccion>Ruta 27 Km 17.250</empDireccion>
		<empMail>general@kaplan.com</empMail>
		<empDepartamento>Canelones</empDepartamento>
		<empClasificacion/>
		<empCertificadoPyme>true</empCertificadoPyme>
	</section-12>
</form>'