enter data recursive
form_approve_data_recursive_yes

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>Y-Zzxf08LsHDZgVG</s>
                        <k>tDxvh7wElNek2gSF</k>
                        <uuid>afe6c52b-12c9-4dd6-89fa-c7ed78d5f61d</uuid>
                        <oop>8297397505</oop>
                        <assignmentOop>8297404161</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>mario</username>
                        <rol>[data-entry-3]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>
						<approved>yes</approved>
                    </section-12>
                </form>'