miem
form_alta_instalacion_1

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
	<internal-section>
		<s/>
		<k/>
		<uuid/>
		<oop/>
		<assignmentOop/>
	</internal-section>
	<section-11>
		<username/>
		<rol/>
		<processId/>
	</section-11>
	<section-12>
		<section-12-iteration>
			<instNombre>Kaplan Cerro Largo</instNombre>
			<instTelefono>654 214 589</instTelefono>
			<instDireccion>Av. Cerro Largo 548</instDireccion>
			<instLocalidad>Fraile Muerto</instLocalidad>
			<instCiudad>Cerro Largo</instCiudad>
			<instDepartamento>Cerro Largo</instDepartamento>
			<instMail>kaplan-cerro-largo@kaplan.com</instMail>
			<instFax>658 548 998</instFax>
		</section-12-iteration>
		<section-12-iteration>
			<instNombre>Kaplan Salto</instNombre>
			<instMail>kaplan-salto@kaplan.com</instMail>
			<instDireccion>Av. Salto 789</instDireccion>
			<instTelefono>965 558 965</instTelefono>
			<instLocalidad>Salto</instLocalidad>
			<instCiudad>Salto</instCiudad>
			<instDepartamento>Salto</instDepartamento>
			<instFax>987 548 547</instFax>
		</section-12-iteration>
	</section-12>
</form>'