all type conditions
form_boolean_exit

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>Fs8Ydj3nA-CAqeWP</s>
                        <k>xAKF0i6eg6S_O8N5</k>
                        <uuid>617caed8-8de9-4c25-a9ce-140eff936b20</uuid>
                        <oop>11685035777</oop>
                        <assignmentOop>11685041921</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[manager][approver][runner][vendor][data-entry-1]</rol>
                        <formId>3269481088</formId>
                    </section-11>
                    <section-12>
                        <name>bruno</name>
                        <amount>12</amount>
                        <time>10:00:00</time>
                        <timeStamp>2016-04-04T04:00:00</timeStamp>
                        <date>2016-04-05</date>
                        <boolean>true</boolean>
                    </section-12>
                </form>'