library forms
form_library_composed_form2

	^'<?xml version="1.0" encoding="UTF-8"?><form><section-2><s>s1</s><k>k1</k><uuid>u1</uuid><oop>op1</oop><assignmentOop>op2</assignmentOop></section-2><section-7><username>bruno</username><rol>admin</rol><processId>12</processId></section-7><section-11><name>john</name><surname>conor</surname></section-11><section-14><street>av end</street><number>123</number><subNumber>543</subNumber></section-14></form>'