visa process
form_check_previous_appliance_1

^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>7Tc1rda-ilWDTbms</s>
                        <k>_6gbxJGdjUGbLDnI</k>
                        <uuid>42d59a2d-c8a5-4db0-9654-7bbae0c20ebf</uuid>
                        <oop>7370578177</oop>
                        <assignmentOop>7370579457</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>andrew vm</username>
                        <rol>[visa manager]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>
                        <citizenName>Bruno</citizenName>
                        <citizenSurname>Buzzi Brassesco</citizenSurname>
                        <originCountry>uruguay</originCountry>
                        <citizenId>37673595</citizenId>
                    </section-12>
                    <section-20>
                        <grid-17>
                                <applianceDate>2014-03-02</applianceDate>
                                <expirationDate>2016-03-09</expirationDate>
                                <oldApplianceResult>passed</oldApplianceResult>
                            </grid-17>
                    </section-20>
                </form>'