simple registration process
form_simple_registration_1

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <section-12>
                        <registrationName>Juan</registrationName>
                        <registrationSurname>Perez</registrationSurname>
                        <originCountry>argentina</originCountry>
                        <registrationId>649874</registrationId>
                    </section-12>
                    <section-16>
                        <registrationDetails>&lt;div&gt;&lt;strong&gt;mmmh&lt;/strong&gt;&lt;/div&gt;</registrationDetails>
                    </section-16>
                </form>'