data entry multirole
form_data_approved_1

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>V2qJXVsTuRWxfFl0</s>
                        <k>ZianBisfDTFKB4mX</k>
                        <uuid>7a90d2fd-d174-474c-97b3-dbc3f8bc4b34</uuid>
                        <oop>8343132929</oop>
                        <assignmentOop>8343134977</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>bruno</username>
                        <rol>[approver]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12><control-12>approved</control-12>
                    </section-12>
                </form>'