dashboard process
form_dashboard_form01

^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>ApGa9W3Ul4nHOlSi</s>
                        <k>y0XV1CcVU7W38FRU</k>
                        <uuid>7d3fa7fd-135a-44eb-bd85-16fd8e27db87</uuid>
                        <oop>7329584385</oop>
                        <assignmentOop>7329585665</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>john</username>
                        <rol>[dashboard-manager]</rol>
                        <processId>65465464</processId>
                    </section-11>
                    <section-12>
                        <invoiceAmount>56000</invoiceAmount>
                        <invoiceTax>12320</invoiceTax>
                        <cost>8500</cost>
                        <costTax>1870</costTax>
                        <deductible>5000</deductible>
                        <deductibleTax>500</deductibleTax>
                        <total>52500</total>
                        <totalWithTaxes>63450</totalWithTaxes>
                        <paymentDate>2019-08-18</paymentDate>
                        <confirmed>true</confirmed>
                        <industry>Finance</industry>
                        <directClient>true</directClient>
                        <country>USA</country>
                        <city>New York</city>
                    </section-12>
                </form>'