miem
form_razones_rechazo

	^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
	<internal-section>
		<s>3r2XieSNo_77YKBH</s>
		<k>kEycpq6V1-MaJQDn</k>
		<uuid>4be93c65-edfa-4e2d-8474-0e91e92db9c7</uuid>
		<oop>9823090433</oop>
		<assignmentOop>9822736641</assignmentOop>
	</internal-section>
	<section-11>
		<username>juan@MIEM</username>
		<rol>[Empresa]</rol>
		<processId>2982381295</processId>
	</section-11>
	<section-1>
		<detalleRechazo>los datos de eficiencia no coinciden con el proyecto</detalleRechazo>
	</section-1>
</form>'