event based gateway
form_loan_application

^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>GzYda_4xduX04QCG</s>
                        <k>JcZbP5haZDlS3aGl</k>
                        <uuid>94398220-aaac-4232-bf8e-38715c8217c4</uuid>
                        <oop>7496192001</oop>
                        <assignmentOop>7496195585</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>andrew vm</username>
                        <rol>[visa manager]</rol>
                        <processId>nil</processId>
                    </section-11>
                    <section-20>
                        <loanTransferDate>2018-04-11</loanTransferDate>
                        <loanAmount>180000</loanAmount>
                        <loanPersonId>123456789</loanPersonId>
                        <loanPersonName>Bruno</loanPersonName>
                        <loanSurname>Buzzi Brassesco</loanSurname>
                        <loanType>direct</loanType>
                    </section-20>
                </form>'