all type conditions
form_time_exit

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>Fs8Ydj3nA-CAqeWP</s>
                        <k>cvGCpPV2w2phO-K4</k>
                        <uuid>402f5dce-e584-4d4a-902b-87ad3cde9062</uuid>
                        <oop>11703155713</oop>
                        <assignmentOop>11703161857</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[manager][approver][runner][vendor][data-entry-1]</rol>
                        <formId>4076811141</formId>
                    </section-11>
                    <section-12>
                        <name>bruno</name>
                        <amount>12</amount>
                        <time>00:01:00</time>
                        <timeStamp>2016-04-17T08:00:00</timeStamp>
                        <date>2016-04-11</date>
                        <boolean>false</boolean>
                    </section-12>
                </form>'