miem
form_documentos_representacion_1

^'<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
	<internal-section>
		<s/>
		<k/>
		<uuid/>
		<oop/>
		<assignmentOop/>
	</internal-section>
	<section-11>
		<username/>
		<rol/>
		<processId/>
	</section-11>
	<section-12>
		<section-12-iteration>
			<docUpload filename="encuesta.ods" mediatype="application/vnd.oasis.opendocument.spreadsheet" size="13961">/fr/service/persistence/crud/agesic-com/documentos-representacion/data/e809b2bf5b58499becc4a1caef6c7ed0440b39bc/3664313e4c1e6fe8a51b6f204f3e9eb146b37837.bin</docUpload>
		</section-12-iteration>
		<section-12-iteration>
			<docUpload filename="sudoers" mediatype="application/octet-stream" size="4181">/fr/service/persistence/crud/agesic-com/documentos-representacion/data/e809b2bf5b58499becc4a1caef6c7ed0440b39bc/3a0b1b29b4349b59882db531e275d6648c86b1fa.bin</docUpload>
		</section-12-iteration>
	</section-12>
	<section-14>
		<proceder>true</proceder>
	</section-14>
</form>'