all gateways process
form_task1: value

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>cINRJyDvEbPhhR86</s>
                        <k>n8pB1SZqRzfmBbZd</k>
                        <uuid>533ff89f-db88-408c-9339-9ecda41c5413</uuid>
                        <oop>8883267073</oop>
                        <assignmentOop>8883273217</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[Vendor][rrhh][ing civil][admin][approver][data-entry-1][entry person][manager]</rol>
                        <formId>nil</formId>
                    </section-11>
                    <section-12>
                        <taskOnevalue>', value,'</taskOnevalue>
                    </section-12>
                </form>'