all type conditions
form_timeStamp_exit

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>Fs8Ydj3nA-CAqeWP</s>
                        <k>yLhzaBi_wjwS4JXx</k>
                        <uuid>7027f686-3858-48a4-ac95-9f488564c611</uuid>
                        <oop>11739942145</oop>
                        <assignmentOop>11739948289</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[manager][approver][runner][vendor][data-entry-1]</rol>
                        <formId>3930049017</formId>
                    </section-11>
                    <section-12>
                        <name>bruno</name>
                        <amount>12</amount>
                        <time>23:59:00</time>
                        <timeStamp>2016-04-11T08:00:00</timeStamp>
                        <date>2050-04-30</date>
                        <boolean>false</boolean>
                    </section-12>
                </form>'