miem
form_alta_representacion_2

^'<?xml version="1.0" encoding="UTF-8"?>
<form xmlns:fr="http://orbeon.org/oxf/xml/form-runner" fr:data-format-version="4.0.0">
	<internal-section>
		<s/>
		<k/>
		<uuid/>
		<oop/>
		<assignmentOop/>
	</internal-section>
	<section-11>
		<username/>
		<rol/>
		<processId/>
	</section-11>
	<section-12>
		<repNombre>Juan</repNombre>
		<repApellido>Gomez Perez</repApellido>
		<repCargo>Encargado Digital</repCargo>
		<repTelefono>789 695 448</repTelefono>
		<repMail>juan@gmail.com</repMail>
		<repTipo>parcial</repTipo>
	</section-12>
	<section-18>
		<repEsTotal>false</repEsTotal>
	</section-18>
</form>'