all type conditions
form_allTypes_name: nameString amount: amountString time: timeString timeStamp: timeStampString date: dateString bool: boolString

	^'<?xml version="1.0" encoding="UTF-8"?><form>
                    <internal-section>
                        <s>Fs8Ydj3nA-CAqeWP</s>
                        <k>2aV_7OtHlDSIAnf2</k>
                        <uuid>e4fb58c4-c7f6-441c-aa62-2a0677f74265</uuid>
                        <oop>11662536449</oop>
                        <assignmentOop>11662543105</assignmentOop>
                    </internal-section>
                    <section-11>
                        <username>alberto</username>
                        <rol>[manager][approver][runner][vendor][data-entry-1]</rol>
                        <formId>2932095122</formId>
                    </section-11>
                    <section-12>
                        <name>',nameString,'</name>
                        <amount>',amountString,'</amount>
                        <time>',timeString,'</time>
                        <timeStamp>',timeStampString,'</timeStamp>
                        <date>',dateString,'</date>
                        <boolean>',boolString,'</boolean>
                    </section-12>
                </form>'